var data =

{
    "objects": [
        {
            "provider_id": 60104,
            "provider_name": "ST ANTHONY NORTH HEALTH CAMPUS",
            "provider_street": "14300 ORCHARD PARKWAY",
            "provider_city": "WESTMINSTER",
            "provider_state": "CO",
            "provider_zip_code": 80023,
            "hrr_description": "CO - Denver",
            "total_discharges": 175,
            "average_covered_charges": 44074.41,
            "average_total_payments": 11581,
            "average_medicare_payments": 9195.18,
            "drg_definition": "470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC",
            "distance": 265,
            "latitude": 39.96,
            "longitude": -315
        },
        {
            "provider_id": 60104,
            "provider_name": "ST ANTHONY NORTH HEALTH CAMPUS",
            "provider_street": "14300 ORCHARD PARKWAY",
            "provider_city": "WESTMINSTER",
            "provider_state": "CO",
            "provider_zip_code": 80023,
            "hrr_description": "CO - Denver",
            "total_discharges": 135,
            "average_covered_charges": 75474.25,
            "average_total_payments": 11637.33,
            "average_medicare_payments": 9854.9,
            "drg_definition": "247 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W/O MCC",
            "distance": 265,
            "latitude": 39.96,
            "longitude": -315
        },
        {
            "provider_id": 60104,
            "provider_name": "ST ANTHONY NORTH HEALTH CAMPUS",
            "provider_street": "14300 ORCHARD PARKWAY",
            "provider_city": "WESTMINSTER",
            "provider_state": "CO",
            "provider_zip_code": 80023,
            "hrr_description": "CO - Denver",
            "total_discharges": 81,
            "average_covered_charges": 95626.89,
            "average_total_payments": 17212.95,
            "average_medicare_payments": 15782.79,
            "drg_definition": "246 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W MCC OR 4+ VESSELS/STENTS",
            "distance": 265,
            "latitude": 39.96,
            "longitude": -315
        },
        {
            "provider_id": 200031,
            "provider_name": "CARY MEDICAL CENTER",
            "provider_street": "163 VAN BUREN RD, SUITE 1",
            "provider_city": "CARIBOU",
            "provider_state": "ME",
            "provider_zip_code": 4736,
            "hrr_description": "ME - Bangor",
            "total_discharges": 175,
            "average_covered_charges": 44074.41,
            "average_total_payments": 11581,
            "average_medicare_payments": 9195.18,
            "drg_definition": "470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC",
            "distance": 4982,
            "latitude": 46.879,
            "longitude": -68.011
        },
        {
            "provider_id": 200052,
            "provider_name": "NORTHERN MAINE MEDICAL CENTER",
            "provider_street": "194 E MAIN STREET",
            "provider_city": "FORT KENT",
            "provider_state": "ME",
            "provider_zip_code": 4743,
            "hrr_description": "ME - Bangor",
            "total_discharges": 175,
            "average_covered_charges": 44074.41,
            "average_total_payments": 11581,
            "average_medicare_payments": 9195.18,
            "drg_definition": "470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC",
            "distance": 4987,
            "latitude": 47.21,
            "longitude": -68.572
        },
        {
            "provider_id": 200018,
            "provider_name": "AROOSTOOK MEDICAL CENTER",
            "provider_street": "PO BOX 151",
            "provider_city": "PRESQUE ISLE",
            "provider_state": "ME",
            "provider_zip_code": 4769,
            "hrr_description": "ME - Bangor",
            "total_discharges": 175,
            "average_covered_charges": 44074.41,
            "average_total_payments": 11581,
            "average_medicare_payments": 9195.18,
            "drg_definition": "470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC",
            "distance": 4991,
            "latitude": 46.679,
            "longitude": -68.002
        },
        {
            "provider_id": 200050,
            "provider_name": "MAINE COAST MEMORIAL HOSPITAL",
            "provider_street": "50 UNION STREET",
            "provider_city": "ELLSWORTH",
            "provider_state": "ME",
            "provider_zip_code": 4605,
            "hrr_description": "ME - Bangor",
            "total_discharges": 175,
            "average_covered_charges": 44074.41,
            "average_total_payments": 11581,
            "average_medicare_payments": 9195.18,
            "drg_definition": "470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC",
            "distance": 5099,
            "latitude": 44.615,
            "longitude": -68.436
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 19,
            "average_covered_charges": 55931,
            "average_total_payments": 11550.95,
            "average_medicare_payments": 9949.58,
            "drg_definition": "286 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 175,
            "average_covered_charges": 44074.41,
            "average_total_payments": 11581,
            "average_medicare_payments": 9195.18,
            "drg_definition": "470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200001,
            "provider_name": "ST JOSEPH HOSPITAL",
            "provider_street": "360 BROADWAY",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 175,
            "average_covered_charges": 44074.41,
            "average_total_payments": 11581,
            "average_medicare_payments": 9195.18,
            "drg_definition": "470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 135,
            "average_covered_charges": 75474.25,
            "average_total_payments": 11637.33,
            "average_medicare_payments": 9854.9,
            "drg_definition": "247 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W/O MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 11,
            "average_covered_charges": 53760.73,
            "average_total_payments": 12673.55,
            "average_medicare_payments": 9884.64,
            "drg_definition": "444 - DISORDERS OF THE BILIARY TRACT W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 23,
            "average_covered_charges": 75390.96,
            "average_total_payments": 13520.96,
            "average_medicare_payments": 12441.13,
            "drg_definition": "417 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 27,
            "average_covered_charges": 69982.41,
            "average_total_payments": 14871.59,
            "average_medicare_payments": 12238.26,
            "drg_definition": "085 - TRAUMATIC STUPOR & COMA, COMA <1 HR W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 34,
            "average_covered_charges": 69886.18,
            "average_total_payments": 15336.88,
            "average_medicare_payments": 14374.18,
            "drg_definition": "480 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 22,
            "average_covered_charges": 50894.64,
            "average_total_payments": 15847.68,
            "average_medicare_payments": 13182.18,
            "drg_definition": "374 - DIGESTIVE MALIGNANCY W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 14,
            "average_covered_charges": 43977.5,
            "average_total_payments": 16110.43,
            "average_medicare_payments": 7527.86,
            "drg_definition": "283 - ACUTE MYOCARDIAL INFARCTION, EXPIRED W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 81,
            "average_covered_charges": 95626.89,
            "average_total_payments": 17212.95,
            "average_medicare_payments": 15782.79,
            "drg_definition": "246 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W MCC OR 4+ VESSELS/STENTS",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 28,
            "average_covered_charges": 71533,
            "average_total_payments": 17267.39,
            "average_medicare_payments": 15877.14,
            "drg_definition": "252 - OTHER VASCULAR PROCEDURES W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        },
        {
            "provider_id": 200033,
            "provider_name": "EASTERN MAINE MEDICAL CENTER",
            "provider_street": "PO BOX 404",
            "provider_city": "BANGOR",
            "provider_state": "ME",
            "provider_zip_code": 4401,
            "hrr_description": "ME - Bangor",
            "total_discharges": 15,
            "average_covered_charges": 92997.8,
            "average_total_payments": 17708.33,
            "average_medicare_payments": 16926.2,
            "drg_definition": "166 - OTHER RESP SYSTEM O.R. PROCEDURES W MCC",
            "distance": 5103,
            "latitude": 44.818,
            "longitude": -68.79
        }
    ],
    "total": 15739,
    "page_number": 1,
    "per_page": 20
}
